name: Build Isabelle

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Isabelle-action
        uses: benkeks/isabelle-action@v1.5
        with:
          args: build -P out -d . Contrasimulation
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: Contrasim-Theory-HTML
          path: "out"
      #- name: Setup Pages
      #  uses: actions/configure-pages@v2
      #- name: Copy documentation
      #  run: "cp /github/home/.isabelle/Isabelle2022/browser_info/Unsorted/Contrasimulation/ ./_site/"
      #- name: Upload artifact
      #  uses: actions/upload-pages-artifact@v1

#  deploy:
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-latest
#    needs: github-pages
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1
